version: 1.0.{build}
environment:
  nodejs_version: "4.4.0"

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm upgrade

test_script:
  # Output useful info for debugging.
  - npm i -g npm
  - node --version
  - npm --version
  # run tests
  - npm test

build_script:
- cmd: npm run make:win

artifacts:
  # Set this to be the name of your output setup exe
  # - path: 'dist\installers\win32\YOUR_APP_NAMESetup.exe'
